###
services:
  - docker:19.03-dind
image: docker:19.03
###
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE: "${REGISTRY_URL}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
###
stages:
  - build
###
build:
  stage: build
  when: manual
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd grocery
    - docker build
      --tag ${IMAGE}
      --file Dockerfile .
    - docker push ${IMAGE}
